### ISSUE TITLE
acceptMatch field missing in scenarios.xsd/ possibly deprecated scenario schema definition

### ISSUE THREAD

**Issue by MrMikeFloyd** [itplr-kosit/validator#32]
**Issue**
When using the [latest release of validator](https://github.com/itplr-kosit/validator/releases/tag/v1.1.0) with this release of its configuration, when accessing the `Result` object after validating an xRechnung, its `acceptRecommendation` will be `UNDEFINED`, even for Schematron violations.

**Examination**
Looking at the [code responsible for determining the accept recommendation](https://github.com/itplr-kosit/validator/blob/master/src/main/java/de/kosit/validationtool/impl/tasks/ComputeAcceptanceAction.java) it becomes obvious that the value depends on the `acceptMatch` element defined in `scenarios.xml`. Using the scenario file and schema from this project though, the element cannot be set as the schema supposedly has been upgraded with the latest release (see [upgraded version](https://github.com/itplr-kosit/validator/blob/master/src/main/model/xsd/scenarios.xsd) in validator project).

**Conclusion**
It seems as if the scenario file/schema definition is deprecated as of version 1.1.0 of the validator. Which configuration is the one to use? Are other parts of the configuration affected by the latest release as well?

**Comment by apenski** [comment]
The `acceptMatch` element is a configuration option introduced in recent validator version. This allows evaluation on API-level. See #27 for details. 

The current validator configuration for xRechnung does not use this yet. 

@rkottmann this isn't a validator problem. It is expected behaviour to give an `acceptRecommendation` of `UNDEFINED` when no `acceptMatch` is configured. It's up to the configuration to determine what's acceptable or not. At least for this release, we have no sensible defaults.

So I guess the ticket was reported correctly to address a problem in the configuration.

**Comment by JannickWeisshaupt** [comment]
Was soll denn der Wert dieses acceptMatch Feldes sein?

**Comment by MrMikeFloyd** [comment]
> Was soll denn der Wert dieses acceptMatch Feldes sein?

Wenn ich den [Quellcode](https://github.com/itplr-kosit/validator/blob/master/src/main/java/de/kosit/validationtool/impl/tasks/ComputeAcceptanceAction.java) korrekt interpretiere, würde das Füllen von `acceptMatch` mit einem beliebigen Wert (`if (isNotBlank(acceptMatch)) {`) das Auslösen der Bewertung (ACCEPTABLE|REJECT) zur Folge haben.

**Comment by JannickWeisshaupt** [comment]
Leider nicht, da getAcceptSelector den Inhalt von acceptMatch ausgibt und dann als xpath auswertet.

**Comment by apenski** [comment]
@JannickWeisshaupt `acceptMatch` belongs to your request/issue #27 and your understanding regarding evaluation is correct. We decided to make no assumption about what is acceptable in the current scenario/configuration. So the configuration needs to define what is acceptable by configuring a xpath-expression which evaluates to boolean value. 

So, at the moment only with a scenario with `acceptMatch` configuration you can get a 'accept recommendation' with a value other than `undefined`. 

Whether this is sensible or maybe better option would be to have defaults like rejecting a file, when it's not schema-compliant or not schematron-compliant or not well-formed at all is up for discussion at the moment. And this not only related to xrechnung.

@MrMikeFloyd,  it's imho a bug, that the xrechnung-configuration does not use this at the moment. @renzok can you please fix this? But the current validator implementation SHOULD be able to process/use existing configurations for pre 1.1.0 releases since this is just an optional feature/element. 

The scenario.xsd is not deprecated at all. We just added some more features and the option to better integrate the validator into custom code by extending the existing API (see [Result.java#L54](https://github.com/itplr-kosit/validator/blob/master/src/main/java/de/kosit/validationtool/api/Check.java#L54) and [Result.java](https://github.com/itplr-kosit/validator/blob/master/src/main/java/de/kosit/validationtool/api/Result.java))

So this is the explanation for the actual feature. @renzok we need to have look what should be done regarding xrechnung-configuration to leverage this feature.

**Comment by apenski** [comment]
We've changed behaviour of the validator in [1.2.0](https://github.com/itplr-kosit/validator/releases/tag/v1.2.0). Schema and schematron errors are now considered when evaluating the `AcceptRecommendation`. Xml without any errors would now evaluate to `getAcceptRecommendation() == 'ACCEPTABLE'`, xml with schema or schematron errors  would now always result in `getAcceptRecommendation() == 'REJECT'`.

However, you _overrule_ schematron errors with an `acceptMatch` configuration in your scenario. See [api documentation](https://github.com/itplr-kosit/validator/blob/master/docs/api.md) for further information about `acceptMatch`
