### ISSUE TITLE
Not Acceptable when validating 01.01a-INVOICE_ubl.xml

### ISSUE THREAD

**Issue by thomaspz** [itplr-kosit/validator#43]
I integrated your validationtool in our product. When validating the example from xrechnung-testsuite

https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/instances/01.01a-INVOICE_ubl.xml

all seems o.k.

The generated Report shows no errors,  

Return values From Report-Object:

```
.isProcessingSuccessful() ==> true
.isSchemaValid(); ==> true
.isWellformed(); ===> true
```

but 

`isAcceptable() ==> false`

but in the "Prüfbericht", there is the sentence:

> Bewertung: Es wird empfohlen das Dokument anzunehmen und weiter zu verarbeiten.

(same report Result, if I run it from command-line)

What should I do? Could I ignore the isAcceptable or is this a bug?

**Comment by apenski** [comment]
This is due to the fact, that  your scenario does not contain an _acceptMatch_ configuration (which will be changed in the next release of the xrechnung-configuration). We've added this functionality as an additional step to check the result but didn't consider existing configurations correctly.

Nevertheless, we've changed behaviour of the validator in [1.2.0](https://github.com/itplr-kosit/validator/releases/tag/v1.2.0) and your example would no evaluate to `isAcceptable() ==> true`  unless you don't configure an `acceptMatch` which would reject the target document. 

See [api documentation](https://github.com/itplr-kosit/validator/blob/v1.2.0/docs/api.md) for further information about `acceptMatch`
